services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
    - 3000:3000
    environment:
    - REACT_APP_GOOGLE_MAPS_API_KEY=${REACT_APP_GOOGLE_MAPS_API_KEY}
    - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL} ## changed these to import from .env.template
    # volumes:
    # - ./src:/app
    depends_on:
    - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
    - 8000:8000
    # volumes:
    # - .:/app